### ISSUE TITLE
Angular Routing Breaks on existing application

### ISSUE THREAD

**Issue by pandabuilt** [paperbits/examples#1]
Hi, thanks so much for your chats and Angular work.  when putting it into an existing app - it breaks routing.

Create routing for App module, create two lazyload modules and put them in your app-routing
{ path: 'one', loadChildren: () => import('./one.module').then(m => m.OneModule) },
    { path: 'two', loadChildren: () => import('./two.module').then(m => m.TwoModule) },

switch between routes. You will see url does not change.  go to one then click to go to two - content changes but url does not change

now remove "import "./paperbits/startup.design"; " from main.ts and restart. Content changes and url now changes too.

**Comment by azaslonov** [comment]
Hi @pandabuilt, thanks for your feedback.

This can be disabled by removing `HistoryRouteHandler` registration from design module [here](https://github.com/paperbits/examples/blob/master/ui-frameworks/angular/src/paperbits/modules/demo.design.module.ts#L27).
